### PR TITLE
Custom Gentx

### PR DESCRIPTION
**Pull request by jkilpatr**
#302  but rebased and with test fixes.

### CODE REVIEW

**Review by marbar3778 — APPROVED** [review]
utACK. we should be good to merge this right?

**Comment by jackzampolin** [comment]
We should. @mvid has it working in his docker refactor branch.

**Review by jackzampolin — APPROVED** [review]

**Review by mvid — APPROVED** [review]

**Comment by jkilpatr** [comment]
This lgtm and I'd like to get it merged but I think we need @fedekunze  to +1 it before it can go in.

**Comment by marbar3778** [comment]
> This lgtm and I'd like to get it merged but I think we need @fedekunze to +1 it before it can go in.

I think someone messed with settings. The codeowners doesn't mean we need to wait for them.

**Review by fedekunze — APPROVED** [review]

**Comment by jkilpatr** [comment]
> > This lgtm and I'd like to get it merged but I think we need @fedekunze to +1 it before it can go in.
> 
> I think someone messed with settings. The codeowners doesn't mean we need to wait for them.

I think that's how this is being interpreted.

> Require review from Code Owners Require an approved review in pull requests including files with a designated code owner. 

I think this option has been enabled since we enabled reviews in general. But I'm not totally sure. If the message github is giving us is correct we either need to disable this option or have @jtremback review.

**Review by jtremback — COMMENTED** [review]
LGTM

**Pull request merged**
