### PR TITLE
Override localhost in the test runner with environment variable

### PR DESCRIPTION
**Pull request by zmanian**
Allows the test runner to be configured with environment variables to enable the docker based test environment.

### CODE REVIEW

**Review by alexanderbez — APPROVED** [review]

**Review by mvid — APPROVED** [review]

**Comment by mvid** [comment]
@alexanderbez sorry, I accidentally deleted your approval

**Comment by alexanderbez** [comment]
All good :)

**Review by alexanderbez — APPROVED** [review]

**Comment by zmanian** [comment]
Block merge on @jkilpatr reviewing.

**Comment by jkilpatr** [comment]
@zmanian  looks good, but did you mean this to merge into fede's branch or master?

**Pull request merged**
